export const ErrorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DUPLICATE_CLIENT: 'DUPLICATE_CLIENT',
    CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  };
  